apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: final
data:

  STUDENT_NAME: "Amrinder; Akash; Shadhana"

  BG_IMAGE_URL: "s3://clo835-group6-096395041427/background.jpg"

  DATABASE: "employees"

  DBHOST: "mysql-service.final.svc.cluster.local"

  DBPORT: "3306"
